export default function Licensing() {
  return (
    <div className="legal-content">
      <div className="container">
        <div className="legal-wrapper">
          <h1 className="legal-title">Content License Agreement</h1>
          <p className="legal-effective-date">Effective Date: February 1, 2025</p>
          <div className="legal-intro">
            <p>This Content License Agreement ("Agreement") governs your rights to use enhanced images created using Shot Lee's AI-powered image enhancement technology ("Enhanced Images"). By using the Shot Lee service to create Enhanced Images, you agree to be bound by this Agreement and Shot Lee's Terms of Service.</p>
          </div>
          <section className="legal-section">
            <h2 className="legal-section-title">1. Definitions</h2>
            <ul className="legal-list">
              <li><strong>"User Images"</strong> means the original photographs you submit to Shot Lee for enhancement.</li>
              <li><strong>"Enhanced Images"</strong> means the professionally enhanced versions of your User Images generated by Shot Lee's proprietary AI technology and algorithms.</li>
              <li><strong>"Shot Lee Technology"</strong> means Shot Lee's proprietary algorithms, enhancement processes, Enhancement Codes, training data, and all intellectual property used to create Enhanced Images.</li>
              <li><strong>"Licensed Territories"</strong> means the United States of America, Canada, Australia, New Zealand, the European Union, the United Kingdom, the United Arab Emirates, Singapore, and India.</li>
            </ul>
          </section>
          <section className="legal-section">
            <h2 className="legal-section-title">2. Ownership and Rights</h2>
            <ul className="legal-list">
              <li><strong>Your User Images.</strong> You retain all ownership rights in your User Images. Shot Lee does not claim any ownership of your original photographs.</li>
              <li><strong>Enhanced Images.</strong> Enhanced Images are created through Shot Lee Technology and are derivative works that incorporate Shot Lee's proprietary intellectual property. As such, Shot Lee reserves certain rights in Enhanced Images as specified in this Agreement.</li>
              <li><strong>Shot Lee Technology.</strong> All intellectual property rights in Shot Lee Technology, including algorithms, enhancement processes, Enhancement Codes, and training data, remain the exclusive property of Shot Lee.</li>
            </ul>
          </section>
          <section className="legal-section">
            <h2 className="legal-section-title">3. License Grant for Licensed Territories</h2>
            <p className="legal-paragraph">For Enhanced Images created by users located in the Licensed Territories, Shot Lee grants you the following rights:</p>
            <ul className="legal-list">
              <li><strong>Personal and Educational Use.</strong> You may use Enhanced Images freely for personal, non-commercial, and educational purposes, including: personal social media posts and profiles, family photo albums, educational projects, personal website portfolios, and non-commercial artistic projects.</li>
              <li><strong>Commercial Use with Attribution.</strong> You may use Enhanced Images for commercial purposes, including advertising, marketing, product packaging, websites, and merchandise, provided you include the following attribution: "Enhanced by Shot Lee" or "Image enhanced using Shot Lee technology." Attribution must be reasonably visible and legible in the context where the Enhanced Image is displayed.</li>
            </ul>
          </section>
          <section className="legal-section">
            <h2 className="legal-section-title">4. Restrictions in Licensed Territories</h2>
            <p className="legal-paragraph">Even in Licensed Territories, you may not:</p>
            <ul className="legal-list">
              <li>Claim that Enhanced Images were created solely by you without use of Shot Lee Technology;</li>
              <li>Reverse engineer, extract, or replicate Shot Lee Technology or Enhancement Codes from Enhanced Images;</li>
              <li>Use Enhanced Images to train competing AI models or image enhancement services;</li>
              <li>Resell or redistribute Enhanced Images as stock photography or in image libraries;</li>
              <li>Use Enhanced Images in any unlawful, defamatory, obscene, or harmful manner;</li>
              <li>Remove, obscure, or alter any copyright notices, watermarks, or metadata embedded in Enhanced Images by Shot Lee.</li>
            </ul>
          </section>
          <section className="legal-section">
            <h2 className="legal-section-title">5. Rights Outside Licensed Territories</h2>
            <p className="legal-paragraph">For Enhanced Images created by users located outside the Licensed Territories, Shot Lee reserves all copyright and intellectual property rights in the Enhanced Images. Users in these territories receive a limited, non-exclusive license to use Enhanced Images solely for personal, non-commercial purposes. Any commercial use requires prior written permission from Shot Lee and may be subject to additional licensing fees.</p>
          </section>
          <section className="legal-section">
            <h2 className="legal-section-title">6. Attribution Requirements</h2>
            <p className="legal-paragraph">When attribution is required or voluntary, acceptable formats include: "Enhanced by Shot Lee", "Image enhanced using Shot Lee technology", "Powered by Shot Lee", or a link to shotlee.com where appropriate.</p>
          </section>
          <section className="legal-section">
            <h2 className="legal-section-title">7. Termination</h2>
            <p className="legal-paragraph">Shot Lee may terminate this license if you violate any terms of this Agreement. Upon termination, you must cease all use of Enhanced Images and delete all copies, except where such images have already been incorporated into completed works distributed prior to termination.</p>
          </section>
          <section className="legal-section">
            <h2 className="legal-section-title">8. Disclaimer of Warranties</h2>
            <p className="legal-paragraph">Enhanced Images are provided "as is" without warranties of any kind. Shot Lee does not guarantee that Enhanced Images will be free from errors or defects, or that they will meet your specific requirements. You are solely responsible for determining the suitability of Enhanced Images for your intended use.</p>
          </section>
          <section className="legal-section">
            <h2 className="legal-section-title">9. Limitation of Liability</h2>
            <p className="legal-paragraph">Shot Lee shall not be liable for any damages arising from your use of Enhanced Images, including any claims from third parties. Your use of Enhanced Images is at your own risk. Shot Lee's total liability shall not exceed the amount you paid for the credits used to generate the Enhanced Images in question.</p>
          </section>
          <section className="legal-section">
            <h2 className="legal-section-title">10. Indemnification</h2>
            <p className="legal-paragraph">You agree to indemnify and hold harmless Shot Lee from any claims, damages, or expenses arising from (i) your use of Enhanced Images in violation of this Agreement, (ii) your failure to provide required attribution, or (iii) any claim that your User Images infringe third-party rights.</p>
          </section>
          <section className="legal-section">
            <h2 className="legal-section-title">11. Changes to This Agreement</h2>
            <p className="legal-paragraph">Shot Lee may modify this Agreement at any time. Material changes will be communicated with reasonable advance notice. Continued use of the Service after changes constitutes acceptance of the modified Agreement.</p>
          </section>
          <section className="legal-section">
            <h2 className="legal-section-title">12. Governing Law</h2>
            <p className="legal-paragraph">This Agreement shall be governed by the laws applicable to the user's location within the Licensed Territories. For users outside Licensed Territories, this Agreement is governed by the laws of the Republic of Singapore.</p>
          </section>
          <section className="legal-section">
            <h2 className="legal-section-title">13. Contact</h2>
            <p className="legal-paragraph">For questions about this Content License Agreement or to request commercial licensing outside Licensed Territories, contact: <a href="mailto:licensing@shotlee.com" className="legal-link">licensing@shotlee.com</a></p>
          </section>
          <div className="legal-divider" />
          <p className="legal-acknowledgment">By using Shot Lee to create Enhanced Images, you acknowledge that you have read, understood, and agree to be bound by this Content License Agreement.</p>
        </div>
      </div>
    </div>
  );
}
